#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [17]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
## Create a Series from Dictionary

data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [6]:
## Dataframe
## create a Dataframe from Dictionary of list

data = {
    'Name': ['Ayush', 'John', 'Jack'],
    'Age': [25,30,45],
    'City': ['Dharamshala', 'New York', 'Florida']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age         City
0  Ayush   25  Dharamshala
1   John   30     New York
2   Jack   45      Florida
<class 'pandas.DataFrame'>

In [8]:
import numpy as np

arr = np.array(df)
print(arr)

[['Ayush' 25 'Dharamshala']
 ['John' 30 'New York']
 ['Jack' 45 'Florida']]

In [92]:
## Create a Dataframe from List of Dictionary
data = [
    {'Name': 'Ayush', 'Age': 26, 'City': 'Dharamshala'},
    {'Name': 'John', 'Age': 30, 'City': 'New York'},
    {'Name': 'Jack', 'Age': 45, 'City': 'Florida'},
    {'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age         City
0  Ayush   26  Dharamshala
1   John   30     New York
2   Jack   45      Florida
3  Bappy   32    Bangalore
<class 'pandas.DataFrame'>

In [14]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [15]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [20]:
## Accessing Data From Dataframe
df

    Name  Age         City
0  Ayush   26  Dharamshala
1   John   30     New York
2   Jack   45      Florida
3  Bappy   32    Bangalore

In [26]:
print(df['Name'])
type(df['Name'])

0    Ayush
1     John
2     Jack
3    Bappy
Name: Name, dtype: str

pandas.Series

In [45]:
print(df.loc[0], end="\n\n\n")
print(df.loc[0,'Name'])

Name          Ayush
Age              26
City    Dharamshala
Name: 0, dtype: object


Ayush

In [48]:
print(df.iloc[0], end="\n\n\n")
print(df.iloc[1,0])

Name          Ayush
Age              26
City    Dharamshala
Name: 0, dtype: object


John

In [55]:
## Accessing a specified element
df.at[2,'Age']

np.int64(45)

In [58]:
df.at[2,'Name']

'Jack'

In [62]:
## Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [63]:
df

    Name  Age         City
0  Ayush   26  Dharamshala
1   John   30     New York
2   Jack   45      Florida
3  Bappy   32    Bangalore

In [64]:
## Data Manipulation with Dataframes
df

    Name  Age         City
0  Ayush   26  Dharamshala
1   John   30     New York
2   Jack   45      Florida
3  Bappy   32    Bangalore

In [81]:
## Adding a column
df['Salary'] = [50000,60000,70000,80000]
df

    Name  Age         City  Salary
0  Ayush   26  Dharamshala   50000
1   John   30     New York   60000
2   Jack   45      Florida   70000
3  Bappy   32    Bangalore   80000

In [82]:
## Remove a column
df.drop('Salary', axis=1)

    Name  Age         City
0  Ayush   26  Dharamshala
1   John   30     New York
2   Jack   45      Florida
3  Bappy   32    Bangalore

In [83]:
df

    Name  Age         City  Salary
0  Ayush   26  Dharamshala   50000
1   John   30     New York   60000
2   Jack   45      Florida   70000
3  Bappy   32    Bangalore   80000

In [84]:
df.drop('Salary', axis=1, inplace= True)

In [76]:
df

    Name  Age         City
0  Ayush   26  Dharamshala
1   John   30     New York
2   Jack   45      Florida
3  Bappy   32    Bangalore

In [93]:
## Add age to the column
df['Age']=df['Age']+1
df

    Name  Age         City
0  Ayush   27  Dharamshala
1   John   31     New York
2   Jack   46      Florida
3  Bappy   33    Bangalore

In [96]:
df.drop(0,inplace=True)

In [97]:
df

    Name  Age       City
1   John   31   New York
2   Jack   46    Florida
3  Bappy   33  Bangalore

In [98]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [103]:
# Display the data types of each column
print("Data Type:\n", df.dtypes, end='\n\n\n')

# Describe the DataFrame
print("Statistical summary:\n", df.describe(), end='\n\n\n')

Data Type:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object


Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [102]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000